# Generated by Django 5.1.1 on 2024-10-10 23:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='game',
            old_name='descripcion',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='game',
            old_name='genero',
            new_name='gender',
        ),
        migrations.RenameField(
            model_name='game',
            old_name='nombre',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='game',
            old_name='plataforma',
            new_name='plataform',
        ),
        migrations.RenameField(
            model_name='game',
            old_name='precio',
            new_name='price',
        ),
        migrations.RenameField(
            model_name='game',
            old_name='fecha_lanzamiento',
            new_name='release_date',
        ),
        migrations.AlterField(
            model_name='game',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='games_imgs/'),
        ),
    ]
