# Generated by Django 5.1.1 on 2024-10-11 00:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_rename_imagen_game_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='game',
            old_name='plataform',
            new_name='platform',
        ),
    ]
