# Generated by Django 5.1.1 on 2024-10-11 05:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_rename_plataform_game_platform'),
    ]

    operations = [
        migrations.RenameField(
            model_name='game',
            old_name='gender',
            new_name='genre',
        ),
    ]
