# Generated by Django 5.1.1 on 2024-10-11 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_rename_gender_game_genre'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='reviews',
            field=models.TextField(blank=True, default=''),
        ),
    ]
